### PR TITLE
Make library stricter

### LINKED ISSUE #2: Does not throw error on invalid address
I was trying to validate an ethereum address form field with `eip55.verify(eip55.encode(address))`. 

I noticed that anything exactly 42 characters is passes.

Screen Shot 2020-12-17 at 3 05 53 PM

Also, **another weird thing** about the above screenshot is that the initial `verify` fails, but the second one succeeds when the result is encoded first. However the `verify` function in `eip55` itself runs the address it is given through `encode` first, so my `eip55.verify(eip55.encode(address))` actually should not be required. 

Maybe it could be considered out of scope (e.g., _"The eip55 package should only be concerned with length and case"_), but it would be really useful if it could also validate that the characters fall in the right range (i.e., "0x" in first 2 characters, [a-f,A-F,0-9] for characters 2-42. It can be done like this:`address.match(/^0x[a-fA-F0-9]{40}$/i)`).

### PR DESCRIPTION
**Pull request by junderw**
Fixes #2

### CODE REVIEW

**Comment by junderw** [comment]
tbh, this should be a patch, since anyone that is encoding an address of 0xzzzz... (which is not possible to encode into an EIP-55 address) or relying on verify(0xzzz...) being true (see #2) already has a broken app and just doesn't know it yet.

The only case where a previously thrown Error will now succeed is if encode is called with a 40 char hex string without the 0x...

previous version will throw since without 0x the length is not 42.
this version will not throw and will append the 0x.

But tbh, as long as there is a valid 40 characters of hex, it can be encoded into a valid EIP-55 address (which this does)

**Comment by cliffhall** [comment]
> tbh, this should be a patch, since anyone that is encoding an address of 0xzzzz... (which is not possible to encode into an EIP-55 address) or relying on verify(0xzzz...) being true (see #2) already has a broken app and just doesn't know it yet.

This isn't necessarily so. In my case, I am attempting to validate a form field that takes an Ethereum address. The user could put anything into it, so I need to know that it is a valid address.

**Comment by cliffhall** [comment]
Seems as expected except 
* encode doesn't throw if the text isn't hex (didn't before, but maybe should?)
* and verify will throw if encode throws (maybe should return false?)
Screen Shot 2020-12-18 at 11 52 50 AM

**Comment by cliffhall** [comment]
It's still allowing bad addresses to verify as long as they've been passed through encode first:

Screen Shot 2020-12-18 at 12 04 28 PM

Perhaps if encode throws when non-hex chars are found among the 40, verify would behave as expected. I know the verify(encode(address)) pattern isn't expected usage, but it should never vary from what verify shows, right?

**Comment by junderw** [comment]
1. Re: your first comment: You are not pulling the correct branch.

You need to checkout the `fix` branch. You are currently using `master` branch (unchanged)

I should probably add some edge cases to the test to prove that this code is correct.

スクリーンショット_2020-12-19_08-48-07

**Comment by junderw** [comment]
2. `verify(encode(x))` is useless because verify is literally "run it through encode and see if equal"... if you run something through encode multiple times it's always the same as just running it one time, the encoded result does not change.

verify(encode(x)) will always be true if it doesn't throw on bad address.

The throwing code is all in encode() so the verify is pointless there.

The point of verify is to take a 40 hex character string with prepended 0x and returning "does the capitalization follow EIP55?"

スクリーンショット_2020-12-19_08-52-09

**Comment by cliffhall** [comment]
Right, I totally get that. But if you look at the screenshot you can see that it doesn’t always produce the same answer as just doing verify, when it should.

**Comment by junderw** [comment]
> it doesn’t always produce the same answer as just doing verify, when it should.

No it should not.

Pretend encode() is just "multiply by 2" then our verify function would be "check if even" (that means it was multiplied by 2 / is divisible by 2, same thing)

If I put 3 into encode, it becomes 6, then if I put it in verify it will be even.

If I run encode THEN verify, verify will always return true.

Therefore it is meaningless to run encode before verify.

It is exactly the same in this library:

encode: 'outputs valid EIP55 address'
verify: 'checks if input is valid EIP55 address'

So logically, the output of encode will always be a valid EIP55 address (or at least it should, the current master is broken, which is why this PR is here to fix it)

**Comment by junderw** [comment]
I think what you're trying to do is account for cases when someone might input a non-EIP55 address (0x plus 40 hex characters)

I have added a `allowOneCase` option to verify on this PR, which will return true IF the input is 0x followed by 40 all-lowercase hex OR 40 all-uppercase-hex, but if there is mixed cases, it will run the hash and verify if the casings verify using EIP55.

If you use verify as normal, it will return false unless the input is a valid EIP55 address casing.

I have also added edge case testing and got the repo up to 100% coverage, so check the new test cases to see how it works / doesn't work with various inputs.

**Comment by junderw** [comment]
In the below code, if we pass `validAddress` to verify it will return false, but if we pass `validAddress` to encode first, it becomes the data in `validEip55Address` which will return true when passed to verify.

```js
// Make sure you've checked out the fix branch
const eip55 = require('.')

// This is the input to encode
const validAddress      = '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

// This is the output
const validEip55Address = '0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa'

// First we verify that the output is correct
console.log(
  eip55.encode(validAddress) === validEip55Address
)
// true

// Also, passing in already encoded address will return the same address
// so multiple passes through encode does not change the result
console.log(
  eip55.encode(validEip55Address) === validEip55Address
)
// true

// verify tells us if EIP55 casing is valid
console.log(eip55.verify(validEip55Address))
// true

// even though this is a valid address, it's not valid EIP55 casing, so false
console.log(eip55.verify(validAddress))
// false
```

**Comment by cliffhall** [comment]
>  think what you're trying to do is account for cases when someone might input a non-EIP55 address (0x plus 40 hex characters)
Here is the case:
Screen Shot 2020-12-18 at 12 04 28 PM

Bad address, has an X in it where only hex should be. On its own, verify doesn't like it. However, run it through encode first and verify gives you a thumbs up.

Verify just calls encode on the input and compares that to the original. So running the output of encode through verify should give the same result. But it doesn't. Encode should have thrown an error because the input was not a valid address. Instead, it seems not to be idempotent, because, well see the screenshot.

**Comment by junderw** [comment]
> Bad address, has an X in it where only hex should be. On its own, verify doesn't like it. However, run it through encode first and verify gives you a thumbs up.

You are using master. Master is incorrect. Do not use master.

**Comment by junderw** [comment]
The current published eip55 library (and master branch of this github repo) is broken.

If you read EIP55, it clearly shows that non-hex characters MUST throw an error during encode.

master/npm does not do that (as evidence by your terminal)

This branch (pull request) fixes that.

So please stop arguing about the behavior of master on a PR that is fixing that behavior.

When fixed, (aka this current pull request branch) verify(encode(x)) MUST always return true.

If you can find a case ON THIS BRANCH (not master) where verify(encode(x)) returns false, then that is a bug that also needs to be fixed.

The following cases will have verify(x) be false while encode(x) does not throw an error (and thus you can run `verify(encode(x))` and always get true):

1. `x` doesn't start with 0x (encode will prepend the 0x for you, so it won't throw)
2. `x` casing is not a valid EIP55 combination of casings

I hope this clears up your confusion.

**Comment by cliffhall** [comment]
My bad. I was on the fix branch earlier but then I deleted and cloned the repo again while switching over to personal access token auth. Forgot to checkout the fix branch.

**Comment by cliffhall** [comment]
Looking good!

**Pull request merged**
