### PR TITLE
Adds un-prefixed addresses

### PR DESCRIPTION
**Pull request by Moejoe90**
This adds support for unprefixed addresses, based on the concept of address length being the only criteria of a valid address.

### CODE REVIEW

**Comment by dcousens** [comment]
@Moejoe90 are these in general usage?
Would `eip55/unprefixed` be a suitable alternative?

**Comment by Moejoe90** [comment]
I don't think the difference is big enough to the extent where you would create a different repo for `eip55/unprefixed` if this is how I understood your question. 

Light wallet for example and other EC addresses generators store addresses without prefix. while it is simple to add a prefix before using this library I think this can be a good addition to reduce code from my side. 

Do you see any reason why this might raise questions?

**Comment by dcousens** [comment]
@Moejoe90 to clarify,  I mean't put the `unprefixed` version in a file named `unprefixed.js`,  in this repository.

You can then `require` it via `eip55/unprefixed`.

**Comment by Moejoe90** [comment]
That would be a valid solution as well

**Pull request closed without merging**
